# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MobilRemake' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'ObjectMapper', '~> 2.2'
    pod 'Toast-Swift', '~> 2.0.0'
    pod 'DGElasticPullToRefresh'
    pod 'ImageSlideshow/Kingfisher'
    pod 'FaveButton', '~> 2.0.3'
    
  # Pods for MobilRemake

  target 'MobilRemakeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MobilRemakeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
